vich_uploader:
    db_driver: orm
    storage: flysystem

    mappings:
        products:
            uri_prefix: '/fichier'
            upload_destination: minio.storage
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        Users:
           uri_prefix: /images/Users
           upload_destination: '%kernel.project_dir%/public/images/Users'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

       

