vich_uploader:
    db_driver: orm
    storage: flysystem

    mappings:
        products:
            uri_prefix: '/fichier'
            upload_destination: minio.storage
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        
